### ISSUE TITLE
打包为发行版本了，不在需要Python环境，打开即用

### ISSUE THREAD

**Issue by ihjycc** [iOSRealRun-cli/iOSRealRun-cli#7]
程序增加自动检测手机版本，并自动下载开发者镜像，理论支持全部版本设备，大小10mb
1.增加自定义速度和自定义路程，达到路程自动暂停
2.优化跑步路线的算法
3.重构拾取路径的网站，让你的路径更方便的拾取

**Comment by ihjycc** [comment]
参考https://github.com/ihjycc/RUN

**Comment by Geniucker** [comment]
老哥打算开源吗
