### ISSUE TITLE
iOS17+ not works

### ISSUE THREAD

**Issue by Geniucker** [iOSRealRun-cli/iOSRealRun-cli#8]

**Comment by Geniucker** [comment]
https://developer.apple.com/forums/thread/730947?answerId=756651022#756651022

**Comment by Geniucker** [comment]
https://github.com/libimobiledevice/libimobiledevice/issues/1460

**Comment by Geniucker** [comment]
libimobiledevice/libimobiledevice#1460

**Comment by Geniucker** [comment]
solutions have been in this release: https://github.com/doronz88/pymobiledevice3/releases/tag/v2.2.0

**Comment by Geniucker** [comment]
sad
pymobiledeivce3 on windows/linux still WIP
from https://github.com/doronz88/pymobiledevice3/issues/502#issuecomment-1661725418

**Comment by Geniucker** [comment]
pymobiledevice3 works on MacOS now
https://github.com/doronz88/pymobiledevice3#working-with-developer-tools-ios--170

**Comment by zfdx123** [comment]
现在有什么解决方案吗，开发者

**Comment by Geniucker** [comment]
还在等pymobiledevice3的进展

**Comment by zfdx123** [comment]
我想用xcode+gpx模拟位置，请问有没有什么适合的生成gpx轨迹的工具，根据咱们的坐标生成轨迹并控制速度

**Comment by Geniucker** [comment]
gpx生成器网上应该能搜到的吧

**Comment by Geniucker** [comment]
https://github.com/doronz88/pymobiledevice3/pull/797

**Comment by Geniucker** [comment]
https://github.com/iOSRealRun-cli/iOSRealRun-cli-17
